### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rac14** [Bumyy/Clutching#4]
Error: Call to a member function getPlayers() on null
File: plugins/Clutch-Core-main/src/ClutchCore/Main
Line: 110
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: ClutchCore v1.0.0

Code:
[101]         $event->setCancelled();
[102]     }
[103] 
[104]     /**
[105]      * @param PlayerQuitEvent $event
[106]      * @return void
[107]      */
[108]     public function onPlayerLeave(PlayerQuitEvent $event) : void{
[109]         $player = $event->getPlayer();
[110]         foreach($this->getServer()->getLevelByName($player->getMap()."-".$player->getName())->getPlayers() as $p){
[111]             $pos = new Position(100, 52, 100, $this->getServer()->getLevelByName($p->getMap()."-".$p->getName()));
[112]             $p->teleport($pos);
[113]             $p->setGamemode(0);
[114]             $p->setSpectating(false);
[115]             $p->sendMessage("§cTeleporting back to your island, because the player you were spectating has left the game!");
[116]             $this->getArenaManager()->giveItems($p, "stopped");
[117]         }
[118]         //delete game and map
[119]         $player->setInGame(false);
[120] 

Backtrace:
#0 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): ClutchCore\Main->onPlayerLeave(object pocketmine\event\player\PlayerQuitEvent)
#1 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object ClutchCore\Main, object pocketmine\event\player\PlayerQuitEvent)
#2 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerQuitEvent)
#3 pmsrc/src/pocketmine/Player(3964): pocketmine\event\Event->call()
#4 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(176): pocketmine\Player->close(object pocketmine\lang\TranslationContainer, string[21] Internal server error)
#5 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[18] 103.165.71.6 37983, object raklib\protocol\EncapsulatedPacket, integer 0)
#6 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
#7 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
#8 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
#9 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
#10 pmsrc/src/pocketmine/Server(2265): pocketmine\snooze\SleeperHandler->sleepUntil(double 1629010191.6725)
#11 pmsrc/src/pocketmine/Server(2105): pocketmine\Server->tickProcessor()
#12 pmsrc/src/pocketmine/Server(1689): pocketmine\Server->start()
#13 pmsrc/src/pocketmine/PocketMine(311): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
#14 pmsrc/src/pocketmine/PocketMine(341): pocketmine\server()
#15 pmsrc(11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by Bumyy** [comment]
This error happened because there was no map created for the player by default! I will make some guides soon about how to make a default world for the plugin to work. It basically generates a world for every player who is playing the game, which is done by unziping a world's zip file. You probably haven't had that on the resources folder!

Fix and better guide is coming up, thanks for the issue!

**Comment by ProtectorYT364** [comment]
Okay :)

**Comment by Bumyy** [comment]
@ProtectorYT364 I fixed it, and also add FromAPI because it doesn't work without that!

**Comment by DevGod6969** [comment]
Ok

**Comment by rac14** [comment]
Ok
